name: Deploy Angular to Azure Static Web App

on:
  push:
    branches:
      - developer

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular App

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production)
        run: npm run build -- --configuration production

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_RIVER_028790710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### ✅ Solo subimos el build ya generado ######
          app_location: "dist/front-smart-financial-assistant/browser"
          ###### ######
